# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


In [2]:
import pandas as pd
df = pd.read_csv('assets/NISPUF17.csv')

# choose necessary column of data
educ_df = df[['EDUC1']]
educ_df.head()

EDUC1
0      4
1      3
2      3
3      4
4      1

In [3]:
# check unique values of column data
educ_df['EDUC1'].unique()

array([4, 3, 1, 2], dtype=int64)

In [4]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    #raise NotImplementedError()
    
    # count proportions of data unique values in data column
    less_than = len(educ_df[educ_df['EDUC1']==1])/len(educ_df)
    high_school = len(educ_df[educ_df['EDUC1']==2])/len(educ_df)
    more_than = len(educ_df[educ_df['EDUC1']==3])/len(educ_df)
    colledge = len(educ_df[educ_df['EDUC1']==4])/len(educ_df)
    
    return {"less than high school":less_than,
                               "high school":high_school,
                               "more than high school but not college":more_than,
                               "college":colledge}

print(proportion_of_education())    
    

{'less than high school': 0.10202002459160373, 'high school': 0.172352011241876, 'more than high school but not college': 0.24588090637625154, 'college': 0.47974705779026877}


In [5]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [6]:
# choose necessary data columns and present it
q2_df = df[['CBF_01','P_NUMFLU']]
q2_df.head()

CBF_01  P_NUMFLU
0       1       NaN
1       2       NaN
2       2       NaN
3       2       3.0
4       1       0.0

In [7]:
# check unique values of CBF column
q2_df['CBF_01'].unique()

array([ 1,  2, 99, 77], dtype=int64)

In [8]:
# collecting rows with necessary data values
bf = q2_df[q2_df['CBF_01'] == 1]
no_bf = q2_df[q2_df['CBF_01'] == 2]

# check lenghts of data
print(len(bf))
print(len(no_bf))

24261
4085


In [9]:
def average_influenza_doses():
    # YOUR CODE HERE
    #raise NotImplementedError()
    
    # count the result
    bf_mean = bf['P_NUMFLU'].mean()
    no_bf_mean = no_bf['P_NUMFLU'].mean()
    return bf_mean, no_bf_mean

# test the fuction result
print (average_influenza_doses())    

(1.8799187420058687, 1.5963945918878317)


In [10]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [11]:
# select necessary columns
q3_df = df[['SEX','P_NUMVRC','HAD_CPOX']]
q3_df.head()

SEX  P_NUMVRC  HAD_CPOX
0    1       NaN         2
1    1       NaN         2
2    2       NaN         2
3    2       1.0         2
4    2       0.0         2

In [12]:
# select necessary rows
q3_df = q3_df[q3_df['P_NUMVRC'] > 0]
q3_df.head()

SEX  P_NUMVRC  HAD_CPOX
3     2       1.0         2
6     2       1.0         2
10    1       1.0         2
12    1       1.0         2
16    1       2.0         2

In [13]:
# select males
male_q3_df = q3_df[q3_df['SEX'] == 1]
male_q3_df.head()

SEX  P_NUMVRC  HAD_CPOX
10    1       1.0         2
12    1       1.0         2
16    1       2.0         2
19    1       1.0         2
21    1       1.0         2

In [14]:
# select females
female_q3_df = q3_df[q3_df['SEX'] == 2]
female_q3_df.head()

SEX  P_NUMVRC  HAD_CPOX
3     2       1.0         2
6     2       1.0         2
20    2       1.0         2
22    2       1.0         2
24    2       1.0         2

In [15]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    #raise NotImplementedError()
    
    # count results
    male_ratio = len(male_q3_df[male_q3_df['HAD_CPOX'] == 1]) / len(male_q3_df[male_q3_df['HAD_CPOX'] == 2])
    female_ratio = len(female_q3_df[female_q3_df['HAD_CPOX'] == 1]) / len(female_q3_df[female_q3_df['HAD_CPOX'] == 2])
    return {'male':male_ratio,'female':female_ratio}

# test function result
print(chickenpox_by_sex())
    

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}


In [16]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [17]:
# select necessary columns
q4_df = df[['P_NUMVRC','HAD_CPOX']]
q4_df.head()

P_NUMVRC  HAD_CPOX
0       NaN         2
1       NaN         2
2       NaN         2
3       1.0         2
4       0.0         2

In [18]:
# drop rows with missing values
q4_df = q4_df.dropna()
q4_df.head()

P_NUMVRC  HAD_CPOX
3       1.0         2
4       0.0         2
6       1.0         2
7       0.0         2
8       0.0         1

In [19]:
# check unique values
q4_df['HAD_CPOX'].unique()

array([ 2,  1, 77], dtype=int64)

In [20]:
# select rows with necessary values
q4_df = q4_df[q4_df['HAD_CPOX'] < 3]

In [21]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    #df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
    #               "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    #corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    #return corr

    # YOUR CODE HERE
    #raise NotImplementedError()
    
    # count and print correlation and pvalue
    corr, pval = stats.pearsonr(q4_df['HAD_CPOX'],q4_df['P_NUMVRC'])
    print('corr = ', corr)
    print('pval = ', pval)
    return corr
    
corr_chickenpox()    

corr =  0.0704487346014804
pval =  2.7780263182866215e-18


0.0704487346014804

In [22]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."


corr =  0.0704487346014804
pval =  2.7780263182866215e-18
